site_id: "13456"
site_name: "Jenkins"
site_description: "CI/CD Tool"
site_version: "1.5"
site_status: "ready to use"
site_la: "Libraries"
site_responsible: {"name":"Devops Team","email":"ameen.mohammed1907@gmail.com"}
site_architects: {"name":"Ameen","email":"ameen.mohammed1907@gmail.com"}
site_last_review_date: "2023-08-30"
site_asil: "ASIL A"
site_permissions: "licensed"
site_price: {"currency":"USD","amount":"19"}
site_usage: ["http://www.harman.com"]
site_license: "yearly license"
site_cyber: "Basic Security Measures"
site_environment: "Cloud"
site_type: "Software"
site_supported_os: "linux"
site_setup_dependencies: "linux"
site_runtime_dependencies: ["http://www.harman.com"]
site_buildtime_dependencies: ["http://www.harman.com"]
site_repositories: ["http://www.harman.com"]
site_requirements: ["http://www.harman.com"]
site_design_documents: ["http://www.harman.com"]
site_release_notes: ["http://www.harman.com"]
site_additional_documentation: ["http://www.harman.com"]
site_interfaces_provided: ["http://www.harman.com"]
site_interfaces_consumed: ["http://www.harman.com"]
site_bug_reporting: ["http://www.harman.com"]
site_activities: "NA"


nav:
  - Introduction: index.md

plugins:
  - techdocs-core
